MVCLaboratorio/Controllers/Cuadrilla2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLaboratorio.Controllers
{
    public class Cuadrilla2Controller : Controller
    {
        // GET: Cuadrilla2
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCLaboratorio/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLaboratorio.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCLaboratorio/Controllers/GPSController.cs
namespace MVCLaboratorio.Controllers
{
    internal class GPSController
    {
    }
}

MVCLaboratorio/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLaboratorio.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCLaboratorio/Controllers/Reclamo2Controller.cs
using BussinesLogic.Controller;
using CommonSolution.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLaboratorio.Controllers
{
    public class Reclamo2Controller : Controller
    {
        // GET: Reclamo2
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listar()
        {
            ReclamoController lc = new ReclamoController();
            List<dtoReclamo> col = lc.getcolReclamo();

            return View(col);
        }
        public ActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AgregarReclamo(dtoReclamo dto)
        {
            ReclamoController cargar = new ReclamoController();
            dtoGPS ubicacion = new dtoGPS();
            ubicacion.latitud = dto.ubicacionLatitud;
            ubicacion.longitud = dto.ubicacionLongitud;
            dtoUsuario usuario = new dtoUsuario();
            usuario.nombreUsuario = dto.nombreUsuario;

            cargar.IngresoReclamo(dto.TipoReclamo, dto.observaciones, ubicacion, usuario);

            return View("Agregar");
        }
    }
}

MVCLaboratorio/Controllers/Zona2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLaboratorio.Controllers
{
    public class Zona2Controller : Controller
    {
        // GET: Zona2
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCLaboratorio/Views/Reclamo/Listar.cshtml
@model IEnumerable<CommonSolution.DTO.dtoReclamo>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ubicacionLatitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ubicacionLongitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nroReclamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaHora)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nroZona)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nroCuadrilla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.observacionCuadrilla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.estadoReclamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombreUsuario)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ubicacionLatitud)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ubicacionLongitud)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nroReclamo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaHora)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nroZona)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nroCuadrilla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.observacionCuadrilla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.estadoReclamo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombreUsuario)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

MVCLaboratorio/Views/Reclamo2/AgregarReclamo.cshtml
@model CommonSolution.DTO.dtoReclamo

@{
    ViewBag.Title = "AgregarReclamo";
}

<h2>AgregarReclamo</h2>

@using (Html.BeginForm("AgregarReclamo", "Reclamo2")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>dtoReclamo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.observaciones, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.observaciones, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.observaciones, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ubicacionLatitud, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ubicacionLatitud, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ubicacionLatitud, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ubicacionLongitud, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ubicacionLongitud, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ubicacionLongitud, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nroReclamo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nroReclamo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nroReclamo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaHora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaHora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaHora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombreUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombreUsuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombreUsuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCLaboratorio/Views/Reclamo2/Listar.cshtml
@model IEnumerable<CommonSolution.DTO.dtoReclamo>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.observaciones)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ubicacionLatitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ubicacionLongitud)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nroReclamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaHora)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nroZona)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nroCuadrilla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.observacionCuadrilla)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.estadoReclamo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombreUsuario)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.observaciones)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ubicacionLatitud)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ubicacionLongitud)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nroReclamo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fechaHora)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nroZona)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nroCuadrilla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.observacionCuadrilla)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.estadoReclamo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombreUsuario)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>